name: hello-world
on: push
jobs:
  foo-job:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4

      - name: foo-step
        env:
          FOO: ${{ vars.MY_VARIABLE }}
          PROD_FOO: ${{ vars.FOO }}
        run: | 
          echo "${PROD_FOO}"
          
