
name: "Foo"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Write to Job Summary
        run: |
          echo "## Job Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Task 1 completed" >> $GITHUB_STEP_SUMMARY
          echo "- ⚠️ Task 2 had warnings" >> $GITHUB_STEP_SUMMARY
          echo "- ❌ Task 3 failed" >> $GITHUB_STEP_SUMMARY


      #      - uses: actions/setup-node@v4
      #        with:
      #          cache: 'npm'
      #          node-version-file: 'package.json'
      #          registry-url: 'https://registry.npmjs.org'
      #
      #      - name: Install dependencies
      #        env:
      #          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      #        run: | 
      #          node --version
      #          npm --version
      #          npm ci --ignore-scripts
      #          npm publish --tag next

