
name: "Foo"

on:
  pull_request: 
    branches:
      - main
      #on:
      #  push:
      #    branches:
      #      - main
  push:
    branches:
      - main

jobs:
#  build:
#    runs-on: 'ubuntu-latest'
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Check labels
#        run: |
#          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"
#
#      - name: Check labelss
#        run: |
#          echo "Labels: ${{ toJson(github.event) }}"
#
#      - name: Write to Job Summary
#        run: |
#          echo "## Job Summary 🚀" >> $GITHUB_STEP_SUMMARY
#          echo "" >> $GITHUB_STEP_SUMMARY
#          echo "- ✅ Task 1 completed" >> $GITHUB_STEP_SUMMARY
#          echo "- ⚠️ Task 2 had warnings" >> $GITHUB_STEP_SUMMARY
#          echo "- ❌ Task 3 failed" >> $GITHUB_STEP_SUMMARY

  imFailing:
    runs-on: 'ubuntu-latest'
    steps:
      - run: exit 1

  imSkipped:
    runs-on: 'ubuntu-latest'
    needs: ['imFailing']
    steps:
      - run: echo "You cant see me"

  check:
    # If any NEEDS are skipped this will not run
    if: ${{ always() }}
    runs-on: 'ubuntu-latest'
    needs: ['imSkipped']
    steps:
    - run: |
        echo "${{ toJson(needs) }}"

    


