
name: "Foo"

on:
  pull_request: 
    branches:
      - main
      #on:
      #  push:
      #    branches:
      #      - main
  push:
    branches:
      - main

jobs:
#  build:
#    runs-on: 'ubuntu-latest'
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Check labels
#        run: |
#          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"
#
#      - name: Check labelss
#        run: |
#          echo "Labels: ${{ toJson(github.event) }}"
#
#      - name: Write to Job Summary
#        run: |
#          echo "## Job Summary 🚀" >> $GITHUB_STEP_SUMMARY
#          echo "" >> $GITHUB_STEP_SUMMARY
#          echo "- ✅ Task 1 completed" >> $GITHUB_STEP_SUMMARY
#          echo "- ⚠️ Task 2 had warnings" >> $GITHUB_STEP_SUMMARY
#          echo "- ❌ Task 3 failed" >> $GITHUB_STEP_SUMMARY

  imFailing:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          exit 0

  imSkipped:
    if: ${{ !always() }}
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo "You cant see me"

  check:
    # If any NEEDS are skipped this will not run if the workflow is cancelled it will be cancelled
    # Cancelled == Failure
    # Skip == Sucess
    if: ${{ !cancelled() }}
    runs-on: 'ubuntu-latest'
    needs: ['imSkipped', 'imFailing']
    env:
      NEEDS: ${{ toJson(needs) }}
    steps:
    - shell: python
      run: |
        import os
        from typing import Dict, Any
        needs: Dict[str, Any] = ${{ toJson(needs) }}

        print(os.environ.get("NEEDS"))

        failed = False
        for k, v in needs.items():
            if v["result"] == "failure":
                print(f"Failing pipeline because job {k} failed")
                failed = True
                break

        if failed:
            exit(1)

    
